### ISSUE TITLE
Detalles acerca de distribución de clases y UML

### ISSUE THREAD

**Issue by NASP-tech** [Walter26/ProyectoPOO#1]
Having issues and doubts about final proyect, we are arguing about the software we need and how many classes do we need, to start our coding process, even though we have the document explanation we also have a question for the diagrams we must construct for the tecnical manual, thank you very much for having us! :)

**Comment by Walter26** [comment]
Lo ideal es empezar con la organización en el tablero, pensar que cosas son necesarias desde un punto de vista de usuario. No es malo empezar a pensar de una vez en el código, pero hace el proceso más tedioso y complicado.

Visualicen que partes son necesarias y clasfíquenlas en el tablero, luego diseñen un esquema de UML de clases solo como orientación, si el esquema no se adapta correctamente a su código, recuerden que es eso nada más, un esquema, pueden moldearlo a como les parezca mejor.

Mi recomendación sería definir primero los recursos gráficos a utilizar, luego pensar el menú, y a partir del menú ver que utilizar. Nunca está de más, tener en el tablero un apartado de investigación para cosas que saben que tienen que hacerse, pero no como implementarse.

PD: solamente el código es en inglés, los issues en español igual que los comentarios del código.
